global:
  scrape_interval: 10s
  evaluation_interval: 10s

scrape_configs:    
# for same VM where prometheus runnig with docker 
  - job_name: 'system-metrics'
    static_configs:
      - targets:
          - 'node-exporter:9100'

  - job_name: 'django'
    metrics_path: '/metrics'
    static_configs:
      - targets:
          - 'backend-oneclickinsight:8000' 
          
#From different VM mertics    
  - job_name: 'Advance-vm-system-metrics'
    static_configs:
      - targets:
          - '20.106.168.41:9100'

  - job_name: 'Advance-vm-django-mertrics'
    metrics_path: '/metrics'
    static_configs:
      - targets:
          - '20.106.168.41:8000' 


