global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'backend_chatbot'
    metrics_path: /metrics
    static_configs:
      - targets:
          - 'backend-chatbot:8000'
  
  - job_name: 'backend_oneclickinsight'
    metrics_path: /metrics
    static_configs:
      - targets:
          - 'backend-oneclickinsight:8001'
          
  - job_name: 'node-exporter'
    static_configs:
      - targets:
          - 'node_exporter:9100'
          
          
          
   # for gathering metrics from another VM where node exporter is running          
scrape_configs:       
  - job_name: 'node-exporter'
    static_configs:
      - targets:
          - '20.127.242.189:9100'




